language: node_js
dist: trusty
sudo: required
node_js: stable
install:
  - npm install
  - npm install -g bower
  - bower install --production
script:
  - npm run -s build
  - bower install
  - npm run -s example:all
after_success:
- >-
  test $TRAVIS_TAG &&
  echo $GITHUB_TOKEN | pulp login &&
  echo y | pulp publish --no-push ||
  git status
